CREATE DATABASE KISHORE

USE KISHORE

CREATE TABLE EMP
(EID INT PRIMARY KEY,
ENAME VARCHAR(50) UNIQUE,
SALARY INT,
DESIGNATION VARCHAR(20),
GENDER VARCHAR(10))

INSERT INTO EMP VALUES(1,'KISHORE',10000,'DEVELOPER')
INSERT INTO EMP(EID,ENAME,SALARY)VALUES(1,'KISHORE',10000)
SELECT * FROM EMP

INSERT INTO EMP VALUES(1,'KISHORE',10000,'DEVELOPER','MALE')
INSERT INTO EMP(EID,ENAME,SALARY)VALUES(2,'BHARANI',10000)

SHOW TABLES;
DESCRIBE EMP;
